"""Added company, title, phone, and profile_pic fields

Revision ID: 1d885f8159f7
Revises: fe4beeed18e5
Create Date: 2025-03-13 13:31:11.873088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d885f8159f7'
down_revision = 'fe4beeed18e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('phone')
        batch_op.drop_column('title')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
